// GENERATED FILE — NON MODIFICARE A MANO.
// Rigenerare con: python scripts/generate_world_countries.py
// Fonte nomi: Unicode CLDR (cldr-localenames-full, en) — licenza Unicode.
// Set codici: ISO 3166-1 alpha-2 (249) + XK (Kosovo, codice utente CLDR/UE).
// Ordinamento: alfabetico sul nome (accenti ignorati). Totale: 250 voci.
//
// PERCHÉ (onboarding C003): la residenza fiscale deve poter essere qualsiasi
// paese del mondo, non solo UE/SEE — l'onboarding non deve bloccare nessuno.

const List<MapEntry<String, String>> kWorldCountries =
    <MapEntry<String, String>>[
  MapEntry('AF', 'Afghanistan'),
  MapEntry('AX', 'Åland Islands'),
  MapEntry('AL', 'Albania'),
  MapEntry('DZ', 'Algeria'),
  MapEntry('AS', 'American Samoa'),
  MapEntry('AD', 'Andorra'),
  MapEntry('AO', 'Angola'),
  MapEntry('AI', 'Anguilla'),
  MapEntry('AQ', 'Antarctica'),
  MapEntry('AG', 'Antigua and Barbuda'),
  MapEntry('AR', 'Argentina'),
  MapEntry('AM', 'Armenia'),
  MapEntry('AW', 'Aruba'),
  MapEntry('AU', 'Australia'),
  MapEntry('AT', 'Austria'),
  MapEntry('AZ', 'Azerbaijan'),
  MapEntry('BS', 'Bahamas'),
  MapEntry('BH', 'Bahrain'),
  MapEntry('BD', 'Bangladesh'),
  MapEntry('BB', 'Barbados'),
  MapEntry('BY', 'Belarus'),
  MapEntry('BE', 'Belgium'),
  MapEntry('BZ', 'Belize'),
  MapEntry('BJ', 'Benin'),
  MapEntry('BM', 'Bermuda'),
  MapEntry('BT', 'Bhutan'),
  MapEntry('BO', 'Bolivia'),
  MapEntry('BA', 'Bosnia and Herzegovina'),
  MapEntry('BW', 'Botswana'),
  MapEntry('BV', 'Bouvet Island'),
  MapEntry('BR', 'Brazil'),
  MapEntry('IO', 'British Indian Ocean Territory'),
  MapEntry('VG', 'British Virgin Islands'),
  MapEntry('BN', 'Brunei'),
  MapEntry('BG', 'Bulgaria'),
  MapEntry('BF', 'Burkina Faso'),
  MapEntry('BI', 'Burundi'),
  MapEntry('KH', 'Cambodia'),
  MapEntry('CM', 'Cameroon'),
  MapEntry('CA', 'Canada'),
  MapEntry('CV', 'Cape Verde'),
  MapEntry('BQ', 'Caribbean Netherlands'),
  MapEntry('KY', 'Cayman Islands'),
  MapEntry('CF', 'Central African Republic'),
  MapEntry('TD', 'Chad'),
  MapEntry('CL', 'Chile'),
  MapEntry('CN', 'China'),
  MapEntry('CX', 'Christmas Island'),
  MapEntry('CC', 'Cocos (Keeling) Islands'),
  MapEntry('CO', 'Colombia'),
  MapEntry('KM', 'Comoros'),
  MapEntry('CG', 'Congo - Brazzaville'),
  MapEntry('CD', 'Congo - Kinshasa'),
  MapEntry('CK', 'Cook Islands'),
  MapEntry('CR', 'Costa Rica'),
  MapEntry('CI', 'Côte d’Ivoire'),
  MapEntry('HR', 'Croatia'),
  MapEntry('CU', 'Cuba'),
  MapEntry('CW', 'Curaçao'),
  MapEntry('CY', 'Cyprus'),
  MapEntry('CZ', 'Czechia'),
  MapEntry('DK', 'Denmark'),
  MapEntry('DJ', 'Djibouti'),
  MapEntry('DM', 'Dominica'),
  MapEntry('DO', 'Dominican Republic'),
  MapEntry('EC', 'Ecuador'),
  MapEntry('EG', 'Egypt'),
  MapEntry('SV', 'El Salvador'),
  MapEntry('GQ', 'Equatorial Guinea'),
  MapEntry('ER', 'Eritrea'),
  MapEntry('EE', 'Estonia'),
  MapEntry('SZ', 'Eswatini'),
  MapEntry('ET', 'Ethiopia'),
  MapEntry('FK', 'Falkland Islands'),
  MapEntry('FO', 'Faroe Islands'),
  MapEntry('FJ', 'Fiji'),
  MapEntry('FI', 'Finland'),
  MapEntry('FR', 'France'),
  MapEntry('GF', 'French Guiana'),
  MapEntry('PF', 'French Polynesia'),
  MapEntry('TF', 'French Southern Territories'),
  MapEntry('GA', 'Gabon'),
  MapEntry('GM', 'Gambia'),
  MapEntry('GE', 'Georgia'),
  MapEntry('DE', 'Germany'),
  MapEntry('GH', 'Ghana'),
  MapEntry('GI', 'Gibraltar'),
  MapEntry('GR', 'Greece'),
  MapEntry('GL', 'Greenland'),
  MapEntry('GD', 'Grenada'),
  MapEntry('GP', 'Guadeloupe'),
  MapEntry('GU', 'Guam'),
  MapEntry('GT', 'Guatemala'),
  MapEntry('GG', 'Guernsey'),
  MapEntry('GN', 'Guinea'),
  MapEntry('GW', 'Guinea-Bissau'),
  MapEntry('GY', 'Guyana'),
  MapEntry('HT', 'Haiti'),
  MapEntry('HM', 'Heard and McDonald Islands'),
  MapEntry('HN', 'Honduras'),
  MapEntry('HK', 'Hong Kong'),
  MapEntry('HU', 'Hungary'),
  MapEntry('IS', 'Iceland'),
  MapEntry('IN', 'India'),
  MapEntry('ID', 'Indonesia'),
  MapEntry('IR', 'Iran'),
  MapEntry('IQ', 'Iraq'),
  MapEntry('IE', 'Ireland'),
  MapEntry('IM', 'Isle of Man'),
  MapEntry('IL', 'Israel'),
  MapEntry('IT', 'Italy'),
  MapEntry('JM', 'Jamaica'),
  MapEntry('JP', 'Japan'),
  MapEntry('JE', 'Jersey'),
  MapEntry('JO', 'Jordan'),
  MapEntry('KZ', 'Kazakhstan'),
  MapEntry('KE', 'Kenya'),
  MapEntry('KI', 'Kiribati'),
  MapEntry('XK', 'Kosovo'),
  MapEntry('KW', 'Kuwait'),
  MapEntry('KG', 'Kyrgyzstan'),
  MapEntry('LA', 'Laos'),
  MapEntry('LV', 'Latvia'),
  MapEntry('LB', 'Lebanon'),
  MapEntry('LS', 'Lesotho'),
  MapEntry('LR', 'Liberia'),
  MapEntry('LY', 'Libya'),
  MapEntry('LI', 'Liechtenstein'),
  MapEntry('LT', 'Lithuania'),
  MapEntry('LU', 'Luxembourg'),
  MapEntry('MO', 'Macao'),
  MapEntry('MG', 'Madagascar'),
  MapEntry('MW', 'Malawi'),
  MapEntry('MY', 'Malaysia'),
  MapEntry('MV', 'Maldives'),
  MapEntry('ML', 'Mali'),
  MapEntry('MT', 'Malta'),
  MapEntry('MH', 'Marshall Islands'),
  MapEntry('MQ', 'Martinique'),
  MapEntry('MR', 'Mauritania'),
  MapEntry('MU', 'Mauritius'),
  MapEntry('YT', 'Mayotte'),
  MapEntry('MX', 'Mexico'),
  MapEntry('FM', 'Micronesia'),
  MapEntry('MD', 'Moldova'),
  MapEntry('MC', 'Monaco'),
  MapEntry('MN', 'Mongolia'),
  MapEntry('ME', 'Montenegro'),
  MapEntry('MS', 'Montserrat'),
  MapEntry('MA', 'Morocco'),
  MapEntry('MZ', 'Mozambique'),
  MapEntry('MM', 'Myanmar (Burma)'),
  MapEntry('NA', 'Namibia'),
  MapEntry('NR', 'Nauru'),
  MapEntry('NP', 'Nepal'),
  MapEntry('NL', 'Netherlands'),
  MapEntry('NC', 'New Caledonia'),
  MapEntry('NZ', 'New Zealand'),
  MapEntry('NI', 'Nicaragua'),
  MapEntry('NE', 'Niger'),
  MapEntry('NG', 'Nigeria'),
  MapEntry('NU', 'Niue'),
  MapEntry('NF', 'Norfolk Island'),
  MapEntry('KP', 'North Korea'),
  MapEntry('MK', 'North Macedonia'),
  MapEntry('MP', 'Northern Mariana Islands'),
  MapEntry('NO', 'Norway'),
  MapEntry('OM', 'Oman'),
  MapEntry('PK', 'Pakistan'),
  MapEntry('PW', 'Palau'),
  MapEntry('PS', 'Palestinian Territories'),
  MapEntry('PA', 'Panama'),
  MapEntry('PG', 'Papua New Guinea'),
  MapEntry('PY', 'Paraguay'),
  MapEntry('PE', 'Peru'),
  MapEntry('PH', 'Philippines'),
  MapEntry('PN', 'Pitcairn Islands'),
  MapEntry('PL', 'Poland'),
  MapEntry('PT', 'Portugal'),
  MapEntry('PR', 'Puerto Rico'),
  MapEntry('QA', 'Qatar'),
  MapEntry('RE', 'Réunion'),
  MapEntry('RO', 'Romania'),
  MapEntry('RU', 'Russia'),
  MapEntry('RW', 'Rwanda'),
  MapEntry('BL', 'Saint Barthélemy'),
  MapEntry('SH', 'Saint Helena'),
  MapEntry('KN', 'Saint Kitts and Nevis'),
  MapEntry('LC', 'Saint Lucia'),
  MapEntry('MF', 'Saint Martin'),
  MapEntry('PM', 'Saint Pierre and Miquelon'),
  MapEntry('VC', 'Saint Vincent and the Grenadines'),
  MapEntry('WS', 'Samoa'),
  MapEntry('SM', 'San Marino'),
  MapEntry('ST', 'São Tomé and Príncipe'),
  MapEntry('SA', 'Saudi Arabia'),
  MapEntry('SN', 'Senegal'),
  MapEntry('RS', 'Serbia'),
  MapEntry('SC', 'Seychelles'),
  MapEntry('SL', 'Sierra Leone'),
  MapEntry('SG', 'Singapore'),
  MapEntry('SX', 'Sint Maarten'),
  MapEntry('SK', 'Slovakia'),
  MapEntry('SI', 'Slovenia'),
  MapEntry('SB', 'Solomon Islands'),
  MapEntry('SO', 'Somalia'),
  MapEntry('ZA', 'South Africa'),
  MapEntry('GS', 'South Georgia and South Sandwich Islands'),
  MapEntry('KR', 'South Korea'),
  MapEntry('SS', 'South Sudan'),
  MapEntry('ES', 'Spain'),
  MapEntry('LK', 'Sri Lanka'),
  MapEntry('SD', 'Sudan'),
  MapEntry('SR', 'Suriname'),
  MapEntry('SJ', 'Svalbard and Jan Mayen'),
  MapEntry('SE', 'Sweden'),
  MapEntry('CH', 'Switzerland'),
  MapEntry('SY', 'Syria'),
  MapEntry('TW', 'Taiwan'),
  MapEntry('TJ', 'Tajikistan'),
  MapEntry('TZ', 'Tanzania'),
  MapEntry('TH', 'Thailand'),
  MapEntry('TL', 'Timor-Leste'),
  MapEntry('TG', 'Togo'),
  MapEntry('TK', 'Tokelau'),
  MapEntry('TO', 'Tonga'),
  MapEntry('TT', 'Trinidad and Tobago'),
  MapEntry('TN', 'Tunisia'),
  MapEntry('TR', 'Türkiye'),
  MapEntry('TM', 'Turkmenistan'),
  MapEntry('TC', 'Turks and Caicos Islands'),
  MapEntry('TV', 'Tuvalu'),
  MapEntry('UM', 'U.S. Outlying Islands'),
  MapEntry('VI', 'U.S. Virgin Islands'),
  MapEntry('UG', 'Uganda'),
  MapEntry('UA', 'Ukraine'),
  MapEntry('AE', 'United Arab Emirates'),
  MapEntry('GB', 'United Kingdom'),
  MapEntry('US', 'United States'),
  MapEntry('UY', 'Uruguay'),
  MapEntry('UZ', 'Uzbekistan'),
  MapEntry('VU', 'Vanuatu'),
  MapEntry('VA', 'Vatican City'),
  MapEntry('VE', 'Venezuela'),
  MapEntry('VN', 'Vietnam'),
  MapEntry('WF', 'Wallis and Futuna'),
  MapEntry('EH', 'Western Sahara'),
  MapEntry('YE', 'Yemen'),
  MapEntry('ZM', 'Zambia'),
  MapEntry('ZW', 'Zimbabwe'),
];
